module.exports = {
  accept: require('./accept/handler'),
  bow: require('./bow/handler'),
  challenge: require('./challenge/handler'),
  git: require('./git/handler'),
  help: require('./help/handler'),
  head: require('./head/handler'),
  prefix: require('./prefix/handler'),
  shoot: require('./shoot/handler'),
  taunt: require('./taunt/handler'),
  body: require('./body/handler'),
  legs: require('./legs/handler'),
  potion: require('./potion/handler'),
  level: require('./level/handler'),
  spectate: require('./spectate/handler'),
  leader: require('./leader/handler'),
  messagesweep: require('./messagesweep/handler'),
  saygen: require('./say/handler'),
  saycol: require('./say/handler2'),
  balance: require('./balance/handler'),
  stock: require('./stock/handler'),
  strength: require('./strength/handler'),
  defense: require('./defense/handler'),
  agility: require('./agility/handler'),
  payout: require('./payout/handler')
};